###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: docker-lamp-mysql
      working_dir: /docker-lamp-mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=test
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root

    php:
      build:
        context: .
        dockerfile: php/Dockerfile
      container_name: docker-lamp-php
      working_dir: /docker-lamp
      volumes:
        - /var/www/html:/var/www/html
        - .:/docker-lamp
      links:
        - mysql
      ports:
        - "80"
